cloud:
    aws:
      region:
        static: us-east-1
      stack:
        auto:
      credentials:
        access-key: AKIA6RMJOLWHU2XS36QE
        secret-key: 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
loggin:
  level:
  com:
    amazonaws:
      internal:
        InstanceMetadataServiceResourceFetcher: error
      util:
        EC2MetadataUtils: error


