cloud:
    aws:
      region:
        static: us-east-1
      stack:
        auto:
      credentials:
        access-key: AKIA6RMJOLWHU2XS36QE
        secret-key: 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
loggin:
  level:
    org:
      hibernate:
        SQL: debug
  com:
    amazonaws:
      internal:
        InstanceMetadataServiceResourceFetcher: error
      util:
        EC2MetadataUtils: error

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/db_book?usSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

